sre.k8s.maintenance: fix missing admin reason
This is a fix for the following runtime error:
AttributeError: 'PoolDepoolClusterRunner' object has no attribute 'admin_reason'

Bug: T277677
Change-Id: I12706e4b46c59939bf2266485a4f19c151197835