reimage: Fix vlan check for VMs
I33e073e5dc993d3c57b2b88b4794689238aa7358 introduced a check for legacy
VLAN's that makes the cookbook fail for VMs:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spicerack/_menu.py", line 199, in run
    runner = self.instance.get_runner(args)
  File "/srv/deployment/spicerack/cookbooks/sre/hosts/reimage.py", line 110, in get_runner
    return ReimageRunner(args, self.spicerack)
  File "/srv/deployment/spicerack/cookbooks/sre/hosts/reimage.py", line 177, in __init__
    if self.netbox_server.access_vlan in LEGACY_VLANS and not self.virtual and not self.args.move_vlan:
  File "/usr/lib/python3/dist-packages/spicerack/netbox.py", line 458, in access_vlan
    netbox_switch_iface = self._find_primary_switch_iface()
  File "/usr/lib/python3/dist-packages/spicerack/netbox.py", line 434, in _find_primary_switch_iface
    raise NetboxError("Server is a virtual machine, can't return a switch interface.")
spicerack.netbox.NetboxError: Server is a virtual machine, can't return a switch interface.

Change-Id: I8a7b38467c3d5a8078c7f4adacfc4d3ba7316d85