sre.gitlab.upgrade: use spicerack reason instead of string
This change passes spiceracks admin_reason to downtime the machine
instead of raw string. This fixes a AttributeError:
'str' object has no attribute 'owner'

Bug: T323569
Change-Id: I2041246f10ef62a21d5b6f4a73a8e9af24452d84