SREDiscoveryNoLVSBatchRunnerBase: Bump waiting interval to 30s
When running the PKI cookbook it ran into a timeout since the change
hadn't converged yet:

File "/usr/lib/python3/dist-packages/spicerack/service.py",
  line 115, in check_service_ips
  raise DiscoveryStateError(
   spicerack.service.DiscoveryStateError: Error checking auth dns for
   pki.discovery.wmnet in codfw: resolved to 10.192.16.172, a
   different IP was expected.

Bug: T346134
Change-Id: I3c01c06592bea05b7d4c7e4675af952b2a0953e6