elastic: add missing restart flag
ERROR THAT LED TO THIS CHANGE
AttributeError: 'Namespace' object has no attribute 'restart'

Bug: T301955
Change-Id: Ic1ee6b9c6fbb251c288c16a86199e40eb700d413