pool_test: Fix mypy error
Add a little wrapper to ensure Pool() receives the mock Spicerack object
itself instead of the fixture

pool_test.py:65: error: Argument "spicerack" to "Pool" has incompatible
type "FixtureFunctionDefinition"; expected "Spicerack"  [arg-type]

Change-Id: I7af21c7cfa1a6320e0875e4a249418356a6a6964