sre.mysql.upgrade: Fix the icinga, second try
It now errors out with:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spicerack/_menu.py", line 234, in run
    raw_ret = runner.run()
  File "/srv/deployment/spicerack/cookbooks/sre/mysql/upgrade.py", line 69, in run
    self.upgrade_host(host)
  File "/srv/deployment/spicerack/cookbooks/sre/mysql/upgrade.py", line 60, in upgrade_host
    with self.icinga_hosts(host).downtimed(self.admin_reason, duration=timedelta(hours=24)):
  File "/usr/lib/python3/dist-packages/spicerack/__init__.py", line 391, in icinga_hosts
    return IcingaHosts(self.icinga_master_host, target_hosts, verbatim_hosts=verbatim_hosts)
  File "/usr/lib/python3/dist-packages/spicerack/icinga.py", line 211, in __init__
    target_hosts = [target_host.split(".")[0] for target_host in target_hosts]
TypeError: 'RemoteHosts' object is not iterable

So RemoteHosts are not NodeSets, because why they would be?

Bug: T239814
Change-Id: I130bdaaa7e2441bf968e0dd7e0d03b2d43a25242