sre.myql.upgrade: Fix missing argument
Currently running it errors out with:
ladsgroup@cumin1001:~$ sudo cookbook sre.mysql.upgrade -h
Exception raised while getting argument parser for cookbook sre.mysql.upgrade:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spicerack/_menu.py", line 329, in _safe_call
    ret_value = func(*args, **kwargs)
TypeError: argument_parser() takes 0 positional arguments but 1 was given

Bug: T239814
Change-Id: I5592b2add1bbdfa8d5abcee54f9a53456d9564ed