setup.py: update dnspython requierments to match spicerack
Th current dnspython pinning is preventing tox from installing the
spicerack > 6.2.2.  Trying to do so manually gives the following error:

  ERROR: pip's dependency resolver does not currently take into account
  all the packages that are installed. This behaviour is the source of
  the following dependency conflicts.
  wikimedia-cookbooks 0.1.dev1014+gcd642e5 requires dnspython==1.16.0,
  but you have dnspython 2.0.0 which is incompatible.

This CR updates the dnspython dependency so that it matches spicerack

Change-Id: I83d11162d313c48b603f0eec955bde7561d14fe7