sre.hosts.reimage: check if the first puppet output is not None
It happened to Tobias that skipping a first failed puppet run caused
and exception like the following:

"""
	**First Puppet run failed, asking the operator what to do**
	Failed to run cookbooks.sre.hosts.reimage.ReimageRunner.run.<locals>._first_puppet_run: Cumin execution failed (exit_code=2)
	==> What do you want to do? "retry" the last command, manually fix the issue and "skip" the last command to continue the execution or completely "abort" the execution.
	> skip
	First Puppet run completed and logged in /var/log/spicerack/sre/hosts/reimage/202205020950_klausman_1339098_ores2002.out
	Exception raised while executing cookbook sre.hosts.reimage:
	Traceback (most recent call last):
	  File "/usr/lib/python3/dist-packages/spicerack/_menu.py", line 234, in run
	    raw_ret = runner.run()
	  File "/srv/deployment/spicerack/cookbooks/sre/hosts/reimage.py", line 502, in run
	    for _, output in puppet_first_run:
	TypeError: 'NoneType' object is not iterable
	**The reimage failed, see the cookbook logs for the details**
"""

A simple fix could be to just check the if the output variable is
not None, since confirm_on_failure can return it.

Change-Id: Ib65b8aad4af3eea0b668846698ecabfbc72c0124